"""Email composer for PUM content delivery.

Composes MIMEMultipart email with copy-paste-ready bilingual captions
and PNG image attachment for Instagram posting.
"""

import os
import logging
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.utils import formatdate, formataddr

from email_sender.smtp_client import send_email

logger = logging.getLogger(__name__)


def format_email_body(post):
    """Format email body with copy-paste-ready sections.

    Args:
        post: Object with attributes: caption_id, caption_en, hashtags (list[str]),
              posting_suggestion, content_pillar, template_type.

    Returns:
        Plain text email body string with bilingual captions, hashtags, and metadata.
    """
    hashtags_str = " ".join(f"#{tag}" for tag in post.hashtags)

    body = f"""PUM Indonesia - Daily Instagram Post
========================================

POSTING SUGGESTION
--------------------
{post.posting_suggestion}

Content pillar: {post.content_pillar}
Template type: {post.template_type}

CAPTION (Bahasa Indonesia)
--------------------
{post.caption_id}

CAPTION (English)
--------------------
{post.caption_en}

HASHTAGS
--------------------
{hashtags_str}

========================================
Image attached: pum_post_{date.today().isoformat()}.png

Generated by PUM Content Generator"""

    return body


def compose_email(post, image_path, from_addr, to_addr):
    """Compose MIMEMultipart email with text body and PNG attachment.

    Args:
        post: Object with GeneratedPost-compatible attributes.
        image_path: Path to PNG image file.
        from_addr: Sender email address.
        to_addr: Recipient email address.

    Returns:
        MIMEMultipart message ready for sending.

    Raises:
        FileNotFoundError: If image_path does not exist or is empty.
    """
    if not os.path.isfile(image_path):
        raise FileNotFoundError(f"Image not found: {image_path}")

    if os.path.getsize(image_path) == 0:
        raise FileNotFoundError(f"Image file is empty: {image_path}")

    msg = MIMEMultipart("mixed")
    msg["From"] = formataddr(("PUM Content Generator", from_addr))
    msg["To"] = to_addr
    msg["Date"] = formatdate(localtime=True)
    msg["Subject"] = f"PUM Instagram Post - {date.today().isoformat()}"

    # Attach text body with utf-8 charset for Bahasa Indonesia support
    msg.attach(MIMEText(format_email_body(post), "plain", "utf-8"))

    # Attach PNG image
    with open(image_path, "rb") as f:
        img_part = MIMEImage(f.read(), _subtype="png")
    img_part.add_header(
        "Content-Disposition", "attachment",
        filename=f"pum_post_{date.today().isoformat()}.png"
    )
    msg.attach(img_part)

    return msg


def send_post_email(post, image_path):
    """Top-level convenience function to compose and send post email.

    Reads GMAIL_ADDRESS, GMAIL_APP_PASSWORD, and RECIPIENT_EMAIL from
    environment variables, composes the email, and sends it.

    Args:
        post: Object with GeneratedPost-compatible attributes.
        image_path: Path to PNG image file.

    Raises:
        ValueError: If any required environment variable is missing.
        FileNotFoundError: If image_path does not exist or is empty.
    """
    gmail_address = os.environ.get("GMAIL_ADDRESS")
    gmail_password = os.environ.get("GMAIL_APP_PASSWORD")
    recipient_email = os.environ.get("RECIPIENT_EMAIL")

    missing = []
    if not gmail_address:
        missing.append("GMAIL_ADDRESS")
    if not gmail_password:
        missing.append("GMAIL_APP_PASSWORD")
    if not recipient_email:
        missing.append("RECIPIENT_EMAIL")
    if missing:
        raise ValueError(f"Missing environment variables: {', '.join(missing)}")

    msg = compose_email(post, image_path, gmail_address, recipient_email)
    send_email(msg)

    logger.info("Post email sent to %s", recipient_email)
